[package]
name = "merk"
description = "Merkle key/value store"
version = "1.0.0-alpha.5"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
time = "0.1.42"
hex = "0.3.2"
colored = "1.8.0"
num_cpus = "1.10.0"
error-chain = "0.12.1"
byteorder = "1.3.2"
jemallocator = "0.3.2"
sled = "0.26.3"

[dependencies.blake2-rfc]
version = "0.2.18"
features = ["bench", "simd_asm"]

[dependencies.rand]
version = "0.7.0"
features = ["small_rng"]

[dependencies.rocksdb]
version = "0.12.3"
default-features = false
